// Mock tyre data for the search results
export interface Tyre {
  id: string
  brand: string
  pattern: string // Renamed from model to match backend
  size: string
  price: number
  imageUrl: string // Renamed from image to match backend
  features: string[]
  // Optional/UI specific fields (some missing in backend)
  type?: "new" | "used"
  newPrice?: number
  usedPrice?: number
  originalPrice?: number
  rating?: number
  reviewCount?: number
  condition?: string
  treadDepth?: number
  freeInstallation?: boolean
  inStock?: boolean
  // Backend fields
  productCode?: string
  warrantyYears?: number
}

export const tyreData: Tyre[] = [
  {
    id: "1",
    brand: "MRF",
    pattern: "ZVTV",
    size: "185/65 R15",
    type: "new",
    price: 4599,
    newPrice: 4599,
    usedPrice: 2800,
    originalPrice: 5499,
    rating: 4.5,
    reviewCount: 234,
    imageUrl: "/mrf-car-tyre.jpg",
    features: ["All Season", "Tubeless", "Warranty 5 Years"],
    freeInstallation: true,
    inStock: true,
  },
  {
    id: "2",
    brand: "Apollo",
    pattern: "Amazer 4G Life",
    size: "185/65 R15",
    type: "new",
    price: 4299,
    newPrice: 4299,
    originalPrice: 4999,
    rating: 4.3,
    reviewCount: 187,
    imageUrl: "/apollo-car-tyre.jpg",
    features: ["Long Life", "Fuel Efficient", "Warranty 4 Years"],
    freeInstallation: true,
    inStock: true,
  },
  {
    id: "3",
    brand: "CEAT",
    pattern: "SecuraDrive",
    size: "185/65 R15",
    type: "new",
    price: 3999,
    newPrice: 3999,
    usedPrice: 2200,
    originalPrice: 4799,
    rating: 4.2,
    reviewCount: 156,
    imageUrl: "/ceat-car-tyre.jpg",
    features: ["Wet Grip", "Silent", "Warranty 4 Years"],
    freeInstallation: true,
    inStock: true,
  },
  {
    id: "4",
    brand: "Bridgestone",
    pattern: "Ecopia EP150",
    size: "185/65 R15",
    type: "new",
    price: 5299,
    newPrice: 5299,
    usedPrice: 3200,
    originalPrice: 6299,
    rating: 4.7,
    reviewCount: 312,
    imageUrl: "/bridgestone-car-tyre.jpg",
    features: ["Eco Friendly", "Low Rolling Resistance", "Warranty 6 Years"],
    freeInstallation: true,
    inStock: true,
  },
  {
    id: "5",
    brand: "MRF",
    pattern: "ZLX",
    size: "185/65 R15",
    type: "used",
    price: 1899,
    newPrice: 4200,
    usedPrice: 1899,
    rating: 4.0,
    reviewCount: 89,
    condition: "Good",
    treadDepth: 6,
    imageUrl: "/used-mrf-tyre.jpg",
    features: ["70% Tread Left", "No Repairs", "30 Day Warranty"],
    freeInstallation: true,
    inStock: true,
  },
  {
    id: "6",
    brand: "Apollo",
    pattern: "Alnac 4G",
    size: "185/65 R15",
    type: "used",
    price: 1599,
    newPrice: 3800,
    usedPrice: 1599,
    rating: 3.8,
    reviewCount: 67,
    condition: "Very Good",
    treadDepth: 7,
    imageUrl: "/used-apollo-tyre.jpg",
    features: ["80% Tread Left", "No Punctures", "30 Day Warranty"],
    freeInstallation: true,
    inStock: true,
  },
  {
    id: "7",
    brand: "Yokohama",
    pattern: "Earth-1",
    size: "185/65 R15",
    type: "new",
    price: 4899,
    newPrice: 4899,
    usedPrice: 2900,
    originalPrice: 5799,
    rating: 4.4,
    reviewCount: 145,
    imageUrl: "/yokohama-car-tyre.jpg",
    features: ["Japanese Quality", "Superior Grip", "Warranty 5 Years"],
    freeInstallation: true,
    inStock: true,
  },
  {
    id: "8",
    brand: "Goodyear",
    pattern: "Assurance",
    size: "185/65 R15",
    type: "new",
    price: 4499,
    newPrice: 4499,
    usedPrice: 2700,
    originalPrice: 5299,
    rating: 4.6,
    reviewCount: 278,
    imageUrl: "/goodyear-car-tyre.jpg",
    features: ["Premium Quality", "All Weather", "Warranty 5 Years"],
    freeInstallation: true,
    inStock: true,
  },
  {
    id: "9",
    brand: "CEAT",
    pattern: "Milaze",
    size: "185/65 R15",
    type: "used",
    price: 1299,
    newPrice: 3500,
    usedPrice: 1299,
    rating: 3.5,
    reviewCount: 45,
    condition: "Good",
    treadDepth: 5,
    imageUrl: "/used-ceat-tyre.jpg",
    features: ["60% Tread Left", "Minor Wear", "15 Day Warranty"],
    freeInstallation: true,
    inStock: false,
  },
  {
    id: "10",
    brand: "JK Tyre",
    pattern: "UX Royale",
    size: "185/65 R15",
    type: "new",
    price: 3799,
    newPrice: 3799,
    usedPrice: 2100,
    originalPrice: 4499,
    rating: 4.1,
    reviewCount: 123,
    imageUrl: "/jk-tyre-car-tyre.jpg",
    features: ["Made in India", "Value for Money", "Warranty 4 Years"],
    freeInstallation: true,
    inStock: true,
  },
  // Duplicated data for pagination testing
  {
    id: "11",
    brand: "MRF",
    pattern: "ZVTV",
    size: "185/65 R15",
    type: "new",
    price: 4599,
    newPrice: 4599,
    usedPrice: 2800,
    originalPrice: 5499,
    rating: 4.5,
    reviewCount: 234,
    imageUrl: "/mrf-car-tyre.jpg",
    features: ["All Season", "Tubeless", "Warranty 5 Years"],
    freeInstallation: true,
    inStock: true,
  },
  {
    id: "12",
    brand: "Apollo",
    pattern: "Amazer 4G Life",
    size: "185/65 R15",
    type: "new",
    price: 4299,
    newPrice: 4299,
    originalPrice: 4999,
    rating: 4.3,
    reviewCount: 187,
    imageUrl: "/apollo-car-tyre.jpg",
    features: ["Long Life", "Fuel Efficient", "Warranty 4 Years"],
    freeInstallation: true,
    inStock: true,
  },
  {
    id: "13",
    brand: "CEAT",
    pattern: "SecuraDrive",
    size: "185/65 R15",
    type: "new",
    price: 3999,
    newPrice: 3999,
    usedPrice: 2200,
    originalPrice: 4799,
    rating: 4.2,
    reviewCount: 156,
    imageUrl: "/ceat-car-tyre.jpg",
    features: ["Wet Grip", "Silent", "Warranty 4 Years"],
    freeInstallation: true,
    inStock: true,
  },
  {
    id: "14",
    brand: "Bridgestone",
    pattern: "Ecopia EP150",
    size: "185/65 R15",
    type: "new",
    price: 5299,
    newPrice: 5299,
    usedPrice: 3200,
    originalPrice: 6299,
    rating: 4.7,
    reviewCount: 312,
    imageUrl: "/bridgestone-car-tyre.jpg",
    features: ["Eco Friendly", "Low Rolling Resistance", "Warranty 6 Years"],
    freeInstallation: true,
    inStock: true,
  },
  {
    id: "15",
    brand: "MRF",
    pattern: "ZLX",
    size: "185/65 R15",
    type: "used",
    price: 1899,
    newPrice: 4200,
    usedPrice: 1899,
    rating: 4.0,
    reviewCount: 89,
    condition: "Good",
    treadDepth: 6,
    imageUrl: "/used-mrf-tyre.jpg",
    features: ["70% Tread Left", "No Repairs", "30 Day Warranty"],
    freeInstallation: true,
    inStock: true,
  },
]

export const brands = ["MRF", "Apollo", "CEAT", "Bridgestone", "Yokohama", "Goodyear", "JK Tyre"]
export const priceRanges = [
  { label: "Under ₹2,000", min: 0, max: 2000 },
  { label: "₹2,000 - ₹3,000", min: 2000, max: 3000 },
  { label: "₹3,000 - ₹4,000", min: 3000, max: 4000 },
  { label: "₹4,000 - ₹5,000", min: 4000, max: 5000 },
  { label: "Above ₹5,000", min: 5000, max: Number.POSITIVE_INFINITY },
]

// Mock mapping of Vehicle -> Tyre Sizes
// Format: Make -> Model -> Variant -> [Sizes]
export const vehicleTyreSizes: Record<string, Record<string, Record<string, string[]>>> = {
  "Maruti Suzuki": {
    "Swift": {
      "LXI": ["165/80 R14"],
      "VXI": ["165/80 R14", "185/65 R15"],
      "ZXI": ["185/65 R15"],
      "ZXI+": ["185/65 R15"],
    },
    "Baleno": {
      "Sigma": ["185/65 R15"],
      "Delta": ["185/65 R15"],
      "Zeta": ["195/55 R16"],
      "Alpha": ["195/55 R16"],
    },
  },
  "Hyundai": {
    "i20": {
      "Magna": ["185/65 R15"],
      "Sportz": ["195/55 R16"],
      "Asta": ["195/55 R16"],
    },
    "Creta": {
      "E": ["205/65 R16"],
      "EX": ["205/65 R16"],
      "S": ["205/65 R16"],
      "SX": ["215/60 R17"],
    },
  },
  "Honda": {
    "City": {
      "V": ["185/60 R15"],
      "VX": ["185/55 R16"],
      "ZX": ["185/55 R16"],
    },
  },
}

export const getAllUniqueSizes = (): string[] => {
  const sizes = new Set<string>()
  tyreData.forEach((t) => sizes.add(t.size))
  return Array.from(sizes).sort()
}
